version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules/
    ports:
      - '${PORT}:${PORT}'
    expose:
      - '${PORT}'